apiVersion: v1
kind: Service
metadata:
  name: toycoon0
  labels:
    app.kubernetes.io/name: toycoon0
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: toycoon0
  ports:
    - name: http
      port: 80
      targetPort: http
