# No clear secrets in git. Ciphertext only; the in-cluster sealed-secrets
# controller unseals it into Secret toycoon0-secrets (envFrom). Sealed (strict
# scope) against the dev cluster cert for namespace sdk-apps-dev.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: toycoon0-secrets
  namespace: sdk-apps-dev
spec:
  encryptedData:
    INTERACTIVE_SECRET: AgCYRbj/yWbl6gEf6CCYxU++6NRD7wRbgvNS0W0DjePg1yCJXBYICWOK5K1y0G/Ra4cXy2X6hmQMJeTEPtxwppt74j3DULwhOyyvrNB+B5U2V9Mmn49ho4qnAbRCOHzG148mVQy0t8tiE2hh/JxxqOMtA6SYG7pZPuzn2FUrchXtk+WVOzczJfNnAbK37TLFUQUfTwy4vFZ323I0hDd2bTytx6yXinNcMW64Cnfhy7ZohbJIHsdETTJ+Vd9snMv5M7t5LjDQ8Q4SUSmCU2ve4QSlTAYle67qty5b6vH88AZMBI1xjhmBHse4YLHXlrrbcVslsSCeW2+TiWuBAE5tbo/VvMoXmYyK2oZrtu2/UPBTEDyO0eHdPNSMfQcA9M9Y0j8ljFPseHk/R6MNfwSURbt7/taRJYAxdidryI8Eciq9pM39srdXeSTQZvybQLHZlsDHt2au/dd2XP1FlNMZ63G5D/du3rtueityf8lANTXZrahvYjpPLkZXe8uXOaMSzMlHra00UMwrAoxADKxP0g6vrfbGZGh6+JrudhNgJFmnAZJBGGo28w4T1v9AT63D2hgGBAwPrh4HKCQoKavOzud+fxgLo6iH6P544BogRgC+BU3xFdujUDKcCIzhKGIUiW6eW1o7ospQxzz/fgVwCucGTzOs5JlITJXeo4+ngXlGjIWw0GzrIuMoa+UrkKOibKugyI1yTEvybWzRJpdlIoL+k8XQRE7GpKPQYjib4yA0FHfZasRP3C9AGI3gVwijU0w=
  template:
    metadata:
      name: toycoon0-secrets
      namespace: sdk-apps-dev
    type: Opaque
